
name: hex_puzzle_flutter_full
description: Hex puzzle prototype
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.20.0

flutter:
  uses-material-design: true
