
name: hex_puzzle_flame_prototype
description: Prototype Flame hex puzzle
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.20.0

flutter:
  uses-material-design: true
